clientFolder/force-app/main/default/objects/Lead/fields/Appointment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Time__c</fullName>
    <label>Appointment Date/Time</label>
    <type>DateTime</type>
</CustomField>

clientFolder/force-app/main/default/objects/Shop_Case__c/Shop_Case__c.object-meta.xml
<CustomObject>
    <label>Shop Case</label>
    <nameField>
        <label>Custom Shop Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

clientFolder/force-app/main/default/objects/Shop_Case__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Oil Change</fullName>
            </value>
            <value>
                <fullName>Tire Rotation</fullName>
            </value>
            <value>
                <fullName>Engine Light On</fullName>
            </value>
            <value>
                <fullName>Full Service</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

clientFolder/force-app/main/default/objects/Shop_Case__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Model 3</fullName>
            </value>
            <value>
                <fullName>Model S</fullName>
            </value>
            <value>
                <fullName>Model X</fullName>
            </value>
            <value>
                <fullName>Model Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

clientFolder/force-app/main/default/classes/appointmentGrabber.cls
public class appointmentGrabber {
	
    @AuraEnabled
    public static List<Lead> fetchSales() {
        return [SELECT FORMAT(appointment_date_time__c), ownerId, phone, email FROM lead WHERE ownerId =: UserInfo.getUserId() AND appointment_date_time__c != null AND appointment_date_time__c > TODAY];
    }
     
    @AuraEnabled
    public static List<Shop_Case__c> fetchShop() {
        return [SELECT name, FORMAT(appointment_date_time__c), vehicle_model__c, service_type__c FROM shop_case__c WHERE ownerId =: UserInfo.getUserId() AND appointment_date_time__c > TODAY];
    }
    
}